// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhQId9mNyROJkHMZAd5fPNYNbPpnYylfk',
    appId: '1:732908813411:web:336d3b50f065bec2228c56',
    messagingSenderId: '732908813411',
    projectId: 'iiitmess-ce93f',
    authDomain: 'iiitmess-ce93f.firebaseapp.com',
    storageBucket: 'iiitmess-ce93f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7ECXNpt1PYzFBW4TfjXu2CZiWajdGTA',
    appId: '1:732908813411:android:1934ec641d784572228c56',
    messagingSenderId: '732908813411',
    projectId: 'iiitmess-ce93f',
    storageBucket: 'iiitmess-ce93f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9MfAsqdSbqXJsVzRDBBjrJjyYoKGBAh0',
    appId: '1:732908813411:ios:018cdbfc7b8cacd7228c56',
    messagingSenderId: '732908813411',
    projectId: 'iiitmess-ce93f',
    storageBucket: 'iiitmess-ce93f.appspot.com',
    iosClientId: '732908813411-9qidilgj5ko9j1j6tr21n7rerf64o4vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9MfAsqdSbqXJsVzRDBBjrJjyYoKGBAh0',
    appId: '1:732908813411:ios:018cdbfc7b8cacd7228c56',
    messagingSenderId: '732908813411',
    projectId: 'iiitmess-ce93f',
    storageBucket: 'iiitmess-ce93f.appspot.com',
    iosClientId: '732908813411-9qidilgj5ko9j1j6tr21n7rerf64o4vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mess',
  );
}
